wifissid = "WiFi SSID"
wifipwd = "PwDpWdPwDpWd"
nm_mac = ""
alarm_host = "sms.ru"
alarm_url = "/sms/send?api_id=********-****-****-****-************&to=797********&msg=Тревога%20по%20движению%20на%20DubosAirNano2"