wifissid = "WiFi SSID"
wifipwd = "PaSsWoRd"
nm_mac = ""
alarm_host = "sms.ru"
alarm_url = "/sms/send?api_id=********-****-****-****-************&to=7978*******&msg=Тревога%20по%20движению%20на%20DubosAirNano2"
